### PR TITLE
setup model change listener based change collector

### PR DESCRIPTION
**Pull request by pvojtechovsky**
Here is the first part of integration of Sniper mode from Spoon https://github.com/INRIA/spoon/pull/1927
This PR enables model change collector.

The second part which is needed was added directly into https://github.com/INRIA/spoon/pull/1927, so checkout latest version of this PR. See commit `use Sniper pretty printer instead of default one` https://github.com/INRIA/spoon/pull/1927/commits/00914388d923f89180b57504cb95f268f000feed

I have not tried how it really works, but these two steps should be enough to setup sniper mode and play with it. Good luck! ;-)

### CODE REVIEW

**Comment by ashutosh1598** [comment]
I have incorporated the changes of this pull request in another branch called [sniper](https://github.com/kth-tcs/sonarqube-repair/tree/sniper). This time it is running without error but I am getting the same/similar diff and it seems that sniper mode is not being used at all.

**Comment by pvojtechovsky** [comment]
please put the breakpoint into constructor of DefaultJavaPrettyPrinter and send me the stacktrace of code which creates DefaultJavaPrettyPrinter, which prints the content of fixed code... note I was not sure which place it was so the sniper printer is probably created on wrong place ...

**Comment by ashutosh1598** [comment]
`"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at spoon.reflect.visitor.DefaultJavaPrettyPrinter.<init>(DefaultJavaPrettyPrinter.java:223)
	  at spoon.Launcher.createPrettyPrinter(Launcher.java:628)
	  at spoon.Launcher.createOutputWriter(Launcher.java:622)
	  at spoon.Launcher.setSourceOutputDirectory(Launcher.java:763)
	  at spoon.Launcher.processArguments(Launcher.java:470)
	  at spoon.Launcher.<init>(Launcher.java:137)
	  at TestHelp.repair(TestHelp.java:43)
	  at Main.main(Main.java:38)
`
This is the thread dump at the breakpoint in constructor of DefaultJavaPrettyPrinter. 

I also put a breakpoint at the change made in [INRIA/spoon@0091438](https://github.com/INRIA/spoon/commit/00914388d923f89180b57504cb95f268f000feed), but the execution finished without reaching that breakpoint.

**Comment by pvojtechovsky** [comment]
So try to override `spoon.Launcher.createPrettyPrinter` by way it returns sniper pretty printer.

**Comment by pvojtechovsky** [comment]
Hi Ashutosh,

I checked your stacktrace and customized spoon to use sniper mode pretty printer. See my last commit here in this PR.

**Comment by ashutosh1598** [comment]
`Exception in thread "main" spoon.SpoonException: ChangeCollector was not attached to the Environment
	at spoon.reflect.visitor.printer.change.ChangesAwareDefaultJavaPrettyPrinter.<init>(ChangesAwareDefaultJavaPrettyPrinter.java:51)
	at TestHelp$1.createPrettyPrinter(TestHelp.java:49)
	at spoon.Launcher.createOutputWriter(Launcher.java:622)
	at spoon.Launcher.setSourceOutputDirectory(Launcher.java:763)
	at spoon.Launcher.processArguments(Launcher.java:470)
	at spoon.Launcher.<init>(Launcher.java:137)
	at TestHelp$1.<init>(TestHelp.java:46)
	at TestHelp.repair(TestHelp.java:46)
	at Main.main(Main.java:38)
`

I am getting this error when I use the last commit. And can I request you to make PRs on the [sniper](https://github.com/kth-tcs/sonarqube-repair/tree/sniper) branch of sonarqube-repair. That way I will be able to directly merge them. I am keeping two separate branches for sniper and normal mode.

**Comment by ashutosh1598** [comment]
I did that but now I'm getting exception when trying to print StandardEnvironment.java of spoon without making any changes to AST. I used sniper mode on some other source code where I didn't get any exception, but still the diff was bad. Things like spaces and brackets are being changed.

**Comment by pvojtechovsky** [comment]
I would try it, but I do not know how to run your tool. What parameters do you use to run it?

**Comment by ashutosh1598** [comment]
You can just run the main function with no arguments. Put the file to be pretty printed in `./source/act/` directory.

**Comment by ashutosh1598** [comment]
The diff is correct when it runs without exception, but it is giving exception for all source code except for very simple files. It can't handle any file with a type cast, for e.g. this one :
    `public class A
    {
        public static void main(String args[])
        {
            int y=5000;
            long x=(long)y;
        }
    }`

**Pull request merged**
